import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }) {

    return (
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>

    );
}
