import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import { Urbanist } from 'next/font/google'
import Script from "next/script";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${urbanist.variable} `}>
      <head>
        <link rel="icon" href="favicon.ico" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2Z5HHQ56CZ"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-2Z5HHQ56CZ');
          `}
        </Script>
        {/* Google Tag Manager */}
        <Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-MZBFFTKQ');
            `,
          }}
        />
      </head>
      <body id="container">
        {/* Google Tag Manager (noscript) */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MZBFFTKQ"
              height="0" width="0" style="display: none; visibility: hidden;"></iframe>`,
          }}
        />
        <Toaster autoClose={20000} position="top-center" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}