import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import "./globals.css"
import { Urbanist } from 'next/font/google'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${urbanist.variable} `}>
      <body id="container">
        
    <div className='main'>
      <h1 className="heading">ATTENTION</h1>
    <p className='child'>
    Infusion Technologies has taken down the website. This illiterate business owner wasted one year by not responding to us, but still, we waited for him and completed the website, which was handed over to him with zero issues. But in the end, he started asking for coding himself. We asked him to explain what he needed to do. He is not a developer. He doesnt even understand English he uses Google Translator to communicate. The website will be up when he sends us an apology letter for defaming and blaming us. 

Thank you.</p>
    </div>
        
        {/* <Toaster autoClose={20000} position="top-center" />
        <Providers>
          {children}
        </Providers> */}
      </body>
    </html>
  );
}
