import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import { Urbanist } from 'next/font/google'
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${urbanist.variable} `}>
      <head>
        <head>
          {/* Google Tag Manager */}
          <Script
            id="gtm-script"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-MZBFFTKQ');
            `,
            }}
          />
        </head>
      </head>
      <body id="container">
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MZBFFTKQ"
          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <Toaster autoClose={20000} position="top-center" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}