export const reviewData = [
    {
        image: '/images/r1.svg',
        name: 'Anil Kumar',
        rating: '5.0',
        date: 'a year ago',
        review: "On this Site you Can absolutely recommend the tours, this website is very helpful for travels .whether a quad tour in the desert, or a boat trip, on one of the islands in Hurghada, great.",
        url: 'https://maps.app.goo.gl/ymE57PrqJiuVC8iXA',
    },
    {
        image: '/images/r1.svg',
        name: 'Muhammad Okasha',
        rating: '5.0',
        date: 'a year ago',
        review: "It was really nice with the guide Mohamed, really friendly and is apart from the rest of guide available here Eden Eiland",
        url: 'https://maps.app.goo.gl/3L5NsLC26sdZ7vn6A',
    },
    {
        image: '/images/r1.svg',
        name: 'Zou Diac',
        rating: '5.0',
        date: 'a year ago    ',
        review: "Had an absolutely amazing day today. Professional from start to finish. Staff was lovely and helpful. Highlight of the trip was snorkelling and the fish swimming all around me definitely not going to forget that. What an experience!!!!",
        url: 'https://maps.app.goo.gl/zeKbXBukV9eKeQG27',
    },
    {
        image: '/images/r1.svg',
        name: 'moh ali',
        rating: '5.0',
        date: 'Two years ago',
        review: "It was a very good experience! The tours was amazing, very well organized. I recommend others to join this tour to save up time and efforts with very well guided tour.",
        url: 'https://maps.app.goo.gl/REXox9JctzMkDYBK7',
    },
    {
        image: '/images/r1.svg',
        name: 'Adam Yasso',
        rating: '5.0',
        date: 'a year ago',
        review: "It is an excellent companyFriendly staff and professional organization.I would recommend for any one to go with them.",
        url: 'https://maps.app.goo.gl/nvVzqVpFi8psPeaU8',
    },
    {
        image: '/images/r1.svg',
        name: 'Sarah sayed',
        rating: '5.0',
        date: 'Two years ago',
        review: "Highly recomended best place to travel with and Mohammed is so friendly u will enjoy the trip with him thanks adventures egypt.",
        url: 'https://maps.app.goo.gl/p5VShKam6LWCU45z8',
    },
    {
        image: '/images/r1.svg',
        name: 'Laura Schweizer',
        rating: '5.0',
        date: 'a year ago',
        review: "We booked a speedboat tour to the dolphins with Mo. It was fantastic. Everything worked out great. The transfer and the tour were wonderful. We were able to snorkel with the dolphins and made a stop at the Maldives island. Mo is very reliable and I can recommend him!",
        url: 'https://maps.app.goo.gl/EfX12684TYbvxHvbA',
    },
    {
        image: '/images/r1.svg',
        name: 'Elena Schrejder',
        rating: '5.0',
        date: 'a year ago',
        review: "Highly recommended We booked a dolphin watching tour by speedboat. That was a very nice experience. Everyone was very enthusiastic and satisfiedHighly recommended We booked a dolphin watching tour by speedboat. ",
        url: 'https://maps.app.goo.gl/kyrBZb9SgxdSLCW39',
    },
]