import dynamic from 'next/dynamic';
const WebHeader = dynamic(() => import('@/components/WebHeader/WebHeader'));
const WebFooter = dynamic(() => import('@/components/WebFooter'), {
    ssr: false
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import "@/app/globals.css";
import { Toaster } from 'react-hot-toast';
export default function Layout({ children }) {

    return (
        <>
            <Toaster autoClose={10000} position="top-center" />
            <WebHeader />
            {children}
            <WebFooter />
        </>
    );
}
